### ISSUE TITLE
Getting Error in Keys

### ISSUE THREAD

**Issue by DDD-User** [hampta/WOG-dump#3] opened 2024-08-25 23:11 UTC
There was already an errors with the keys, then I inserted keys without updating in program and it work, but after updates I still get errors. But, surprisingly, a pair of keys was written to a file

![screen1](https://github.com/user-attachments/assets/999d10ce-72fc-4839-92b4-6ac621f3b12e)

**Comment by hampta** [comment] 2024-08-26 00:30
🤔🤔🤔, Okay, I'll double check everything.

**Comment by hampta** [comment] 2024-08-26 00:30
🤔🤔🤔, Okay, I'll double check everything.

**Comment by Luffyyy** [comment] 2024-08-26 01:00
I think the issue is that when trying to get keys, the response doesn't have a sync value and therefore fails 
https://github.com/hampta/WOG-dump/blob/main/wog_dump.py#L123

**Comment by hampta** [comment] 2024-08-26 04:11
> I think the issue is that when trying to get keys, the response doesn't have a sync value and therefore fails https://github.com/hampta/WOG-dump/blob/main/wog_dump.py#L123

I found the root of the problem - just don't update keys, because only Ukrainian IPs have full access to keys without unlocking. I checked in the game, if you login from German/USA VPN, most of the weapons are not available, but if you disconnect and re-enter - everything is open

**Closed** 2024-08-26 04:22 UTC
